name: chemformer-laptop
block_size: 256
n_encoder_layer: 4
n_decoder_layer: 4
n_head: 4
d_model: 256
dropout: 0.1
use_submersion: false
submersion_pooling_method: "mean"
immersion_activation: "silu"
use_kv_cache: false
use_gate: false
use_qk_norm: true
ffn_multiplier: 2.5 # Ensures FFN intermediate size (640) is divisible by 64.
rope_theta: 10000.0
layer_scale_init: 0.0001
electra_task: false
encoder_attention_type: "mha"
max_relative_positions: 256
tie_word_embeddings: false
use_liger_ff: true
use_liger_norm: true
use_liger_rope: true
use_default_liger_ff: false
use_default_liger_norm: false
use_default_liger_rope: false

