name: rust_build_env

channels:
  - conda-forge
  - defaults

dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - binutils_impl_linux-64=2.45
  - binutils_linux-64=2.45
  - bzip2=1.0.8
  - c-ares=1.34.6
  - ca-certificates=2025.11.12
  - clang=21.1.7
  - clang-21=21.1.7
  - clang_impl_linux-64=21.1.7
  - clangxx=21.1.7
  - clangxx_impl_linux-64=21.1.7
  - cmake=4.2.1
  - compiler-rt=21.1.7
  - compiler-rt21=21.1.7
  - compiler-rt21_linux-64=21.1.7
  - compiler-rt_linux-64=21.1.7
  - gcc_impl_linux-64=15.2.0
  - gcc_linux-64=15.2.0
  - gxx_impl_linux-64=15.2.0
  - gxx_linux-64=15.2.0
  - icu=78.1
  - kernel-headers_linux-64=5.14.0
  - keyutils=1.6.3
  - krb5=1.21.3
  - ld_impl_linux-64=2.45
  - libclang=21.1.7
  - libclang-cpp21.1=21.1.7
  - libclang13=21.1.7
  - libcurl=8.17.0
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.3
  - libgcc=15.2.0
  - libgcc-devel_linux-64=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libiconv=1.18
  - libllvm21=21.1.8
  - liblzma=5.8.1
  - libnghttp2=1.67.0
  - libsanitizer=15.2.0
  - libssh2=1.11.1
  - libstdcxx=15.2.0
  - libstdcxx-devel_linux-64=15.2.0
  - libstdcxx-ng=15.2.0
  - libuv=1.51.0
  - libxml2=2.15.1
  - libxml2-16=2.15.1
  - libzlib=1.3.1
  - llvm-openmp=21.1.8
  - make=4.4.1
  - ncurses=6.5
  - openssl=3.6.0
  - rhash=1.4.6
  - rust=1.92.0
  - rust-std-x86_64-unknown-linux-gnu=1.92.0
  - sysroot_linux-64=2.34
  - tzdata=2025c
  - zstd=1.5.7
