# @package _global_
task:
  name: finetune_uspto
  pretrain_checkpoint: 'path/to/your/zinc_pretrained.pth' # TODO: Set this to the actual path of your pretrained model

dataset:
  name: uspto_sep
  lmdb_path: data/uspto_sep.lmdb
  augment_prob: 1.0

# Override model config for fine-tuning
model:
  electra_task: false
  use_submersion: false
