# @package _global_
task:
  name: pretrain_zinc
  pretrain_checkpoint: null

dataset:
  name: zinc
  lmdb_path: data/zinc.lmdb
  mask_prob: 0.30
  span_len: 3
  augment_prob: 1.0
  span_mask_proportion: 1.0
  span_random_proportion: 0.0
