tokens:
- '#'
- $
- '%'
- (
- )
- '*'
- +
- '-'
- .
- /
- '0'
- '1'
- '2'
- '3'
- '4'
- '5'
- '6'
- '7'
- '8'
- '9'
- ':'
- <
- <EOS>
- <PAD>
- <SOS>
- <UNK>
- =
- '>'
- '?'
- '@'
- Ac
- Ag
- Al
- Am
- Ar
- As
- At
- Au
- B
- Ba
- Be
- Bh
- Bi
- Bk
- Br
- C
- Ca
- Cd
- Ce
- Cf
- Cl
- Cm
- Cn
- Co
- Cr
- Cs
- Cu
- Db
- Ds
- Dy
- Er
- Es
- Eu
- F
- Fe
- Fl
- Fm
- Fr
- Ga
- Gd
- Ge
- H
- He
- Hf
- Hg
- Ho
- Hs
- I
- In
- Ir
- K
- Kr
- La
- Li
- Lr
- Lu
- Lv
- Md
- Mg
- Mn
- Mo
- Mt
- N
- Na
- Nb
- Nd
- Ne
- Ni
- No
- Np
- O
- Og
- Os
- P
- Pa
- Pb
- Pd
- Pm
- Po
- Pr
- Pt
- Pu
- Ra
- Rb
- Re
- Rf
- Rg
- Rh
- Rn
- Ru
- S
- Sb
- Sc
- Se
- Sg
- Si
- Sm
- Sn
- Sr
- Ta
- Tb
- Tc
- Te
- Th
- Ti
- Tl
- Tm
- Ts
- U
- V
- W
- Xe
- Y
- Yb
- Zn
- Zr
- '[17O]'
- '[Ag+2]'
- '[Ag+]'
- '[Ag-]'
- '[Ag]'
- '[Al+2]'
- '[Al+3]'
- '[Al+]'
- '[AlH2-]'
- '[AlH3]'
- '[AlH4-]'
- '[AlH]'
- '[Al]'
- '[Ar]'
- '[As+]'
- '[As-]'
- '[AsH3]'
- '[AsH]'
- '[As]'
- '[At]'
- '[Au-]'
- '[Au]'
- '[B+2]'
- '[B+3]'
- '[B+]'
- '[B-]'
- '[B@-]'
- '[B@@-]'
- '[BH-]'
- '[BH2-]'
- '[BH3-]'
- '[BH4-]'
- '[BH]'
- '[B]'
- '[Ba+2]'
- '[Ba]'
- '[Be+2]'
- '[Bi+3]'
- '[Bi]'
- '[Br+2]'
- '[Br+]'
- '[Br-]'
- '[Br]'
- '[C+4]'
- '[C+]'
- '[C-]'
- '[C@@H]'
- '[C@@]'
- '[C@H]'
- '[C@]'
- '[CH+]'
- '[CH-]'
- '[CH2+]'
- '[CH2-]'
- '[CH2]'
- '[CH3+]'
- '[CH3-]'
- '[CH3]'
- '[CH]'
- '[C]'
- '[Ca+2]'
- '[Ca]'
- '[Cd+2]'
- '[Cd+]'
- '[Cd]'
- '[Ce+2]'
- '[Ce+3]'
- '[Ce+4]'
- '[Ce]'
- '[Cl+2]'
- '[Cl+3]'
- '[Cl+]'
- '[Cl-]'
- '[Cl]'
- '[Co+2]'
- '[Co+3]'
- '[Co+]'
- '[Co]'
- '[Cr+2]'
- '[Cr+3]'
- '[Cr+6]'
- '[Cr]'
- '[Cs+]'
- '[Cs]'
- '[Cu+2]'
- '[Cu+3]'
- '[Cu+]'
- '[Cu]'
- '[Dy+3]'
- '[Eu+3]'
- '[F-]'
- '[F]'
- '[Fe+2]'
- '[Fe+3]'
- '[Fe-3]'
- '[Fe-4]'
- '[Fe]'
- '[Ga+2]'
- '[Ga+3]'
- '[Ga+]'
- '[Ga]'
- '[GeH4]'
- '[GeH]'
- '[Ge]'
- '[H+]'
- '[H-]'
- '[H]'
- '[He]'
- '[Hf+4]'
- '[Hf]'
- '[Hg+2]'
- '[Hg+]'
- '[Hg]'
- '[I+2]'
- '[I+3]'
- '[I+]'
- '[I-]'
- '[IH+]'
- '[IH2+3]'
- '[IH2+]'
- '[IH2]'
- '[IH]'
- '[I]'
- '[In+3]'
- '[In+]'
- '[In]'
- '[Ir]'
- '[K+]'
- '[KH]'
- '[K]'
- '[Kr]'
- '[La+3]'
- '[La]'
- '[Li+]'
- '[LiH]'
- '[Li]'
- '[Mg+2]'
- '[Mg+]'
- '[MgH2]'
- '[Mg]'
- '[Mn+2]'
- '[Mn+3]'
- '[Mn]'
- '[Mo]'
- '[N+3]'
- '[N+]'
- '[N-]'
- '[N@+]'
- '[N@@+]'
- '[N@@H+]'
- '[N@@]'
- '[N@]'
- '[NH+]'
- '[NH-]'
- '[NH2+]'
- '[NH2-]'
- '[NH2]'
- '[NH3+]'
- '[NH4+]'
- '[NH]'
- '[N]'
- '[Na+]'
- '[Na]'
- '[Nd+3]'
- '[Nd+]'
- '[Nd]'
- '[Ni+2]'
- '[Ni+3]'
- '[Ni+]'
- '[Ni]'
- '[O+]'
- '[O-2]'
- '[O-]'
- '[OH+]'
- '[OH-]'
- '[OH2+]'
- '[OH]'
- '[O]'
- '[Os]'
- '[P+3]'
- '[P+5]'
- '[P+]'
- '[P-3]'
- '[P-]'
- '[P@+]'
- '[P@@+]'
- '[P@@H]'
- '[P@@]'
- '[P@H]'
- '[P@]'
- '[PH+]'
- '[PH2+]'
- '[PH2]'
- '[PH3+]'
- '[PH3]'
- '[PH4+]'
- '[PH4]'
- '[PH5]'
- '[PH]'
- '[P]'
- '[Pb+2]'
- '[Pb+3]'
- '[Pb+4]'
- '[Pb]'
- '[Pd+2]'
- '[Pd+]'
- '[Pd-2]'
- '[Pd-4]'
- '[Pd-]'
- '[PdH2]'
- '[Pd]'
- '[Pr+3]'
- '[Pt+2]'
- '[Pt+3]'
- '[Pt-]'
- '[Pt]'
- '[Ra]'
- '[Rb+]'
- '[Rb]'
- '[Re]'
- '[Rh+2]'
- '[Rh+3]'
- '[Rh+]'
- '[Rh]'
- '[Ru+2]'
- '[Ru-2]'
- '[RuH3]'
- '[Ru]'
- '[S+]'
- '[S-2]'
- '[S-]'
- '[S@+]'
- '[S@@+]'
- '[S@@H]'
- '[S@@]'
- '[S@]'
- '[SH+]'
- '[SH-]'
- '[SH2+]'
- '[SH2]'
- '[SH3+]'
- '[SH3]'
- '[SH]'
- '[S]'
- '[Sb+5]'
- '[Sb]'
- '[Sc+3]'
- '[Sc]'
- '[Se+]'
- '[Se-2]'
- '[Se-]'
- '[SeH-]'
- '[SeH2]'
- '[SeH]'
- '[Se]'
- '[Si+]'
- '[Si-]'
- '[Si@@]'
- '[Si@]'
- '[SiH-]'
- '[SiH2]'
- '[SiH3-]'
- '[SiH3]'
- '[SiH4]'
- '[SiH]'
- '[Si]'
- '[Sm+2]'
- '[Sm+3]'
- '[Sm]'
- '[Sn+2]'
- '[Sn+3]'
- '[Sn+4]'
- '[Sn+]'
- '[SnH2+]'
- '[SnH2]'
- '[SnH3]'
- '[SnH4+2]'
- '[SnH4]'
- '[SnH6+3]'
- '[SnH]'
- '[Sn]'
- '[Sr+2]'
- '[SrH2]'
- '[Sr]'
- '[Ta+2]'
- '[Ta+5]'
- '[TaH3]'
- '[Ta]'
- '[Te-]'
- '[TeH2]'
- '[TeH]'
- '[Te]'
- '[Ti+2]'
- '[Ti+3]'
- '[Ti+4]'
- '[Ti+5]'
- '[Ti+]'
- '[Ti]'
- '[Tl+2]'
- '[Tl+3]'
- '[Tl+]'
- '[Tl]'
- '[V+3]'
- '[V+4]'
- '[V]'
- '[W]'
- '[Xe]'
- '[Y+3]'
- '[Yb+3]'
- '[Yb]'
- '[Zn+2]'
- '[Zn+]'
- '[Zn]'
- '[Zr+2]'
- '[Zr+3]'
- '[Zr+4]'
- '[Zr+]'
- '[Zr]'
- '[b-]'
- '[c+]'
- '[c-]'
- '[cH-]'
- '[c]'
- '[n+]'
- '[n-]'
- '[nH+]'
- '[nH]'
- '[n]'
- '[o+]'
- '[p+]'
- '[s+]'
- '[sH+]'
- '[se+]'
- '[se]'
- '[te+]'
- '[te]'
- \
- b
- c
- n
- o
- p
- s
- se
- te
- '~'
metadata:
  total_tokens: 619322829
  unique_tokens: 492
  total_smiles_processed: 13571708
  created_date: 2026-01-04 03:02:48
  source: from_file
  charset: SMILES
